name: Build evil-tools

on:
  pull_request:
    paths-ignore:
      - 'scripts/**'

jobs:
  build:
    name: Build evil-tools
    runs-on: self-hosted
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
        id: go

      - name: Print Go version
        run: go version

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Build evil-tools
        run: go build -v .
