name: Build evil-tools

on:
  pull_request:
    paths-ignore:
      - 'scripts/**'

jobs:
  build:
    name: Build evil-tools
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: false
        id: go

      - name: Print Go version
        run: go version

      - name: Build evil-tools
        run: go build -v .

  build_docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag evil-tools:latest
